/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GeometriaRouteImport } from './routes/geometria'
import { Route as ConstrucaoRouteImport } from './routes/construcao'
import { Route as IndexRouteImport } from './routes/index'

const GeometriaRoute = GeometriaRouteImport.update({
  id: '/geometria',
  path: '/geometria',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstrucaoRoute = ConstrucaoRouteImport.update({
  id: '/construcao',
  path: '/construcao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/construcao': typeof ConstrucaoRoute
  '/geometria': typeof GeometriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/construcao': typeof ConstrucaoRoute
  '/geometria': typeof GeometriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/construcao': typeof ConstrucaoRoute
  '/geometria': typeof GeometriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/construcao' | '/geometria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/construcao' | '/geometria'
  id: '__root__' | '/' | '/construcao' | '/geometria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConstrucaoRoute: typeof ConstrucaoRoute
  GeometriaRoute: typeof GeometriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/geometria': {
      id: '/geometria'
      path: '/geometria'
      fullPath: '/geometria'
      preLoaderRoute: typeof GeometriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construcao': {
      id: '/construcao'
      path: '/construcao'
      fullPath: '/construcao'
      preLoaderRoute: typeof ConstrucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConstrucaoRoute: ConstrucaoRoute,
  GeometriaRoute: GeometriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
